//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:2.0.50727.42
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap blank {
            get {
                object obj = ResourceManager.GetObject("blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dtl {
            get {
                object obj = ResourceManager.GetObject("dtl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap erz5 {
            get {
                object obj = ResourceManager.GetObject("erz5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gb {
            get {
                object obj = ResourceManager.GetObject("gb", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Getreide_auswahl {
            get {
                object obj = ResourceManager.GetObject("Getreide_auswahl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Getreide_benutzt {
            get {
                object obj = ResourceManager.GetObject("Getreide_benutzt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Getreide_frei {
            get {
                object obj = ResourceManager.GetObject("Getreide_frei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Getreide_gebaut {
            get {
                object obj = ResourceManager.GetObject("Getreide_gebaut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap getreide4 {
            get {
                object obj = ResourceManager.GetObject("getreide4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gold6 {
            get {
                object obj = ResourceManager.GetObject("gold6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap grey {
            get {
                object obj = ResourceManager.GetObject("grey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap haus_01_an {
            get {
                object obj = ResourceManager.GetObject("haus_01_an", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap haus_01_aus {
            get {
                object obj = ResourceManager.GetObject("haus_01_aus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap haus_01_frei {
            get {
                object obj = ResourceManager.GetObject("haus_01_frei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap haus_02_an {
            get {
                object obj = ResourceManager.GetObject("haus_02_an", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap haus_02_aus {
            get {
                object obj = ResourceManager.GetObject("haus_02_aus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap haus_02_frei {
            get {
                object obj = ResourceManager.GetObject("haus_02_frei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap haus_03_an {
            get {
                object obj = ResourceManager.GetObject("haus_03_an", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap haus_03_aus {
            get {
                object obj = ResourceManager.GetObject("haus_03_aus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap haus_03_frei {
            get {
                object obj = ResourceManager.GetObject("haus_03_frei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap haus_04_an {
            get {
                object obj = ResourceManager.GetObject("haus_04_an", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap haus_04_aus {
            get {
                object obj = ResourceManager.GetObject("haus_04_aus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap haus_04_frei {
            get {
                object obj = ResourceManager.GetObject("haus_04_frei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap haus_05_an {
            get {
                object obj = ResourceManager.GetObject("haus_05_an", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap haus_05_aus {
            get {
                object obj = ResourceManager.GetObject("haus_05_aus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap haus_05_frei {
            get {
                object obj = ResourceManager.GetObject("haus_05_frei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap haus_06_an {
            get {
                object obj = ResourceManager.GetObject("haus_06_an", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap haus_06_aus {
            get {
                object obj = ResourceManager.GetObject("haus_06_aus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap haus_06_frei {
            get {
                object obj = ResourceManager.GetObject("haus_06_frei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap holz1 {
            get {
                object obj = ResourceManager.GetObject("holz1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lehm2 {
            get {
                object obj = ResourceManager.GetObject("lehm2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PlaceCity {
            get {
                return ResourceManager.GetStream("PlaceCity", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PlaceKnight {
            get {
                return ResourceManager.GetStream("PlaceKnight", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PlaceRoad {
            get {
                return ResourceManager.GetStream("PlaceRoad", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream PlaceSettlement {
            get {
                return ResourceManager.GetStream("PlaceSettlement", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap playermap_ok {
            get {
                object obj = ResourceManager.GetObject("playermap_ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_01_an {
            get {
                object obj = ResourceManager.GetObject("ritter_01_an", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_01_aus {
            get {
                object obj = ResourceManager.GetObject("ritter_01_aus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_01_ben {
            get {
                object obj = ResourceManager.GetObject("ritter_01_ben", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_01_frei {
            get {
                object obj = ResourceManager.GetObject("ritter_01_frei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_02_an {
            get {
                object obj = ResourceManager.GetObject("ritter_02_an", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_02_aus {
            get {
                object obj = ResourceManager.GetObject("ritter_02_aus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_02_ben {
            get {
                object obj = ResourceManager.GetObject("ritter_02_ben", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_02_frei {
            get {
                object obj = ResourceManager.GetObject("ritter_02_frei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_03_an {
            get {
                object obj = ResourceManager.GetObject("ritter_03_an", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_03_aus {
            get {
                object obj = ResourceManager.GetObject("ritter_03_aus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_03_ben {
            get {
                object obj = ResourceManager.GetObject("ritter_03_ben", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_03_frei {
            get {
                object obj = ResourceManager.GetObject("ritter_03_frei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_04_an {
            get {
                object obj = ResourceManager.GetObject("ritter_04_an", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_04_aus {
            get {
                object obj = ResourceManager.GetObject("ritter_04_aus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_04_ben {
            get {
                object obj = ResourceManager.GetObject("ritter_04_ben", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_04_frei {
            get {
                object obj = ResourceManager.GetObject("ritter_04_frei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_05_an {
            get {
                object obj = ResourceManager.GetObject("ritter_05_an", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_05_aus {
            get {
                object obj = ResourceManager.GetObject("ritter_05_aus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_05_ben {
            get {
                object obj = ResourceManager.GetObject("ritter_05_ben", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_05_frei {
            get {
                object obj = ResourceManager.GetObject("ritter_05_frei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_06_an {
            get {
                object obj = ResourceManager.GetObject("ritter_06_an", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_06_aus {
            get {
                object obj = ResourceManager.GetObject("ritter_06_aus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_06_ben {
            get {
                object obj = ResourceManager.GetObject("ritter_06_ben", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_06_frei {
            get {
                object obj = ResourceManager.GetObject("ritter_06_frei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ritter_06_frei1 {
            get {
                object obj = ResourceManager.GetObject("ritter_06_frei1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream RollDice {
            get {
                return ResourceManager.GetStream("RollDice", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap schaaf3 {
            get {
                object obj = ResourceManager.GetObject("schaaf3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stadt_01_an {
            get {
                object obj = ResourceManager.GetObject("stadt_01_an", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stadt_01_aus {
            get {
                object obj = ResourceManager.GetObject("stadt_01_aus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stadt_01_frei {
            get {
                object obj = ResourceManager.GetObject("stadt_01_frei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stadt_02_an {
            get {
                object obj = ResourceManager.GetObject("stadt_02_an", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stadt_02_aus {
            get {
                object obj = ResourceManager.GetObject("stadt_02_aus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stadt_02_frei {
            get {
                object obj = ResourceManager.GetObject("stadt_02_frei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stadt_03_an {
            get {
                object obj = ResourceManager.GetObject("stadt_03_an", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stadt_03_aus {
            get {
                object obj = ResourceManager.GetObject("stadt_03_aus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stadt_03_frei {
            get {
                object obj = ResourceManager.GetObject("stadt_03_frei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stadt_04_an {
            get {
                object obj = ResourceManager.GetObject("stadt_04_an", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stadt_04_aus {
            get {
                object obj = ResourceManager.GetObject("stadt_04_aus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap stadt_04_frei {
            get {
                object obj = ResourceManager.GetObject("stadt_04_frei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap strasse_120_an {
            get {
                object obj = ResourceManager.GetObject("strasse_120_an", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap strasse_120_aus {
            get {
                object obj = ResourceManager.GetObject("strasse_120_aus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap strasse_120_frei {
            get {
                object obj = ResourceManager.GetObject("strasse_120_frei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap strasse_30_an {
            get {
                object obj = ResourceManager.GetObject("strasse_30_an", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap strasse_30_aus {
            get {
                object obj = ResourceManager.GetObject("strasse_30_aus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap strasse_30_frei {
            get {
                object obj = ResourceManager.GetObject("strasse_30_frei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap strasse_90_an {
            get {
                object obj = ResourceManager.GetObject("strasse_90_an", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap strasse_90_aus {
            get {
                object obj = ResourceManager.GetObject("strasse_90_aus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap strasse_90_frei {
            get {
                object obj = ResourceManager.GetObject("strasse_90_frei", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream Trade {
            get {
                return ResourceManager.GetStream("Trade", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap uebersicht1 {
            get {
                object obj = ResourceManager.GetObject("uebersicht1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
